# Capstone 2: Business Analysis with Python

### EmporiUm: Student Bookstore Chain Sales Analysis

This capstone project is about the analysis of sales in Connecticut and New York of the East Region. Utilizing python and multiple python libraries like: NumPy, pandas, and Matplotlib.

- **Region:** East
    - **Territory:** Connecticut
        - **Manager:** Ana Jilani
        - **StoreID:** 865 - 872
    - **Territory:** New York
        - **Manager:** Ana Jilani
        - **StoreID:** 840 - 851

The analysis includes:

- Monthly total revenue trend
- Ranking of store performances
- Customer purchasing behavior
- Product category analysis
- Next quarter marketing recommendation

In [30]:
# Import necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### Import files

In [31]:
cust_list = pd.read_csv('customer_list.csv')

In [32]:
cust_list.head()

     cust_id|date|time|name|email|phone|sms-opt-out
0  1|2023-03-15|08:45:12|Rachel|rachel@centralper...
1  2|2023-05-22|12:30:45|R. Geller|rossg@centralp...
2  3|2023-07-09|18:15:27|Monica Geller|chefmonica...
3  4|2023-09-01|21:05:33|Chandler Bing|chandlerb@...
4  5|2023-11-18|14:22:10|Joey|howyoudoing@central...

In [33]:
cust_list.info()

<class 'pandas.DataFrame'>
RangeIndex: 521 entries, 0 to 520
Data columns (total 1 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   cust_id|date|time|name|email|phone|sms-opt-out   521 non-null    str
dtypes: str(1)
memory usage: 4.2 KB

In [34]:
prod_categories = pd.read_csv('ProductCategories.csv')

In [35]:
prod_categories.head()

   CategoryID                  Category SubcategoryID           Subcategory
0         120  Technology & Accessories       120-tab               Tablets
1         120  Technology & Accessories       120-cal           Calculators
2         120  Technology & Accessories       120-sof     Software Download
3         120  Technology & Accessories       120-hea            Headphones
4         120  Technology & Accessories       120-ext  External Accessories

In [36]:
prod_categories.info()

<class 'pandas.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   CategoryID     52 non-null     int64
 1   Category       52 non-null     str
 2   SubcategoryID  52 non-null     str
 3   Subcategory    52 non-null     str
dtypes: int64(1), str(3)
memory usage: 1.8 KB

In [37]:
products = pd.read_csv('Products.csv')

In [38]:
products.head()

    Prod Num                        Product  CategoryID SubcategoryID
0  105248-IT               TCL NXTPAPER 10s         120       120-tab
1  105249-IT  Dell Latitude 7320 Detachable         120       120-tab
2  105250-IT                     Realme Pad         120       120-tab
3  105251-IT             Lenovo Tab P12 Pro         120       120-tab
4  105252-IT        Microsoft Surface Pro 9         120       120-tab

In [39]:
products.info()

<class 'pandas.DataFrame'>
RangeIndex: 669 entries, 0 to 668
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Prod Num       669 non-null    str
 1   Product        669 non-null    str
 2   CategoryID     669 non-null    int64
 3   SubcategoryID  669 non-null    str
dtypes: int64(1), str(3)
memory usage: 21.0 KB

In [40]:
store_detail = pd.read_csv('StoreDetail.csv')

In [41]:
store_detail.head()

  Store Location     State  Store ID Territory Manager Region  Region Director
0         Aurora  Colorado       701          Jim Heck   West  Cassie Chambers
1       Berthoud  Colorado       702          Jim Heck   West  Cassie Chambers
2        Boulder  Colorado       703          Jim Heck   West  Cassie Chambers
3    Castle Rock  Colorado       704          Jim Heck   West  Cassie Chambers
4         Denver  Colorado       705          Jim Heck   West  Cassie Chambers

In [42]:
store_detail.info()

<class 'pandas.DataFrame'>
RangeIndex: 111 entries, 0 to 110
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Store Location     111 non-null    str
 1   State              111 non-null    str
 2   Store ID           111 non-null    int64
 3   Territory Manager  111 non-null    str
 4   Region             111 non-null    str
 5   Region Director    111 non-null    str
dtypes: int64(1), str(5)
memory usage: 5.3 KB

In [43]:
store_sales = pd.read_csv('StoreSales.csv')

In [44]:
store_sales.head()

  Transaction Date  Store ID  RewardsID  Prod Num  Sale Amount
0         1/1/2022       702        NaN  105349-M         8.00
1         1/1/2022       704        NaN  105350-T       144.00
2         1/1/2022       705        NaN  105351-M        44.00
3         1/1/2022       705        NaN  105352-M        47.61
4         1/1/2022       705        NaN  105353-A        20.36

In [45]:
store_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 335129 entries, 0 to 335128
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction Date  335129 non-null  str
 1   Store ID          335129 non-null  int64
 2   RewardsID         34943 non-null   float64
 3   Prod Num          335129 non-null  str
 4   Sale Amount       335129 non-null  float64
dtypes: float64(2), int64(1), str(2)
memory usage: 12.8 MB

## Core Marketing Analysis

**Who are the territory managers for the sales territories assigned? What are the store IDs and cities for the stores in each assigned sales territory?**

In [46]:
ct_info = store_detail[store_detail['State'] == 'Connecticut']
ct_id = ct_info["Store ID"].tolist()  # created a variable to store all Store IDs within Connecticut.
                                      # In the case, my manager adds in another store.
ct_info
# Connecticut: 865-872, Ellen Lemon

,Store Location,State,Store ID,Territory Manager,Region,Region Director
18,Bridgeport,Connecticut,865,Ellen Lemon,East,Ana Jilani
19,Darien,Connecticut,866,Ellen Lemon,East,Ana Jilani
20,Hartford,Connecticut,867,Ellen Lemon,East,Ana Jilani
21,Litchfield County,Connecticut,868,Ellen Lemon,East,Ana Jilani
22,New Haven,Connecticut,869,Ellen Lemon,East,Ana Jilani
23,New London,Connecticut,870,Ellen Lemon,East,Ana Jilani
24,Old Saybrook,Connecticut,871,Ellen Lemon,East,Ana Jilani
25,Waterbury,Connecticut,872,Ellen Lemon,East,Ana Jilani

In [47]:
ny_info = store_detail[store_detail['State'] == 'New York']
ny_id = ny_info['Store ID'].tolist()
ny_info
# New York: 840-851, See Ellefson

   Store Location     State  Store ID Territory Manager Region Region Director
86         Albany  New York       840      See Ellefson   East      Ana Jilani
87        Buffalo  New York       841      See Ellefson   East      Ana Jilani
88         Elmira  New York       842      See Ellefson   East      Ana Jilani
89         Ithaca  New York       843      See Ellefson   East      Ana Jilani
90         Oswego  New York       844      See Ellefson   East      Ana Jilani
91    Plattsburgh  New York       845      See Ellefson   East      Ana Jilani
92    Poestenkill  New York       846      See Ellefson   East      Ana Jilani
93      Rochester  New York       847      See Ellefson   East      Ana Jilani
94       Syracuse  New York       848      See Ellefson   East      Ana Jilani
95       Brooklyn  New York       849      See Ellefson   East      Ana Jilani
96       New York  New York       850      See Ellefson   East      Ana Jilani
97         Queens  New York       851      See Ellefson   East      Ana Jilani

**What is monthly total revenue for in-store sales in each of the two sales territories, over the full period covered by the data?**

In [48]:
# Finding Connecticut's monthly total revenue
ct_sales = store_sales[store_sales['Store ID'].isin(ct_id)]
ct_sales

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
130            1/1/2022       865        NaN   105370-S         8.45
131            1/1/2022       867        NaN  105330-IT      1376.44
132            1/1/2022       867        NaN   105371-T       216.90
133            1/1/2022       870        NaN   105372-S         7.85
134            1/1/2022       871        NaN   105373-T        88.42
...                 ...       ...        ...        ...          ...
335089       12/31/2025       871        NaN   105727-M        50.96
335090       12/31/2025       871      307.0   105429-T        71.80
335091       12/31/2025       871        NaN  105325-IT      1717.70
335092       12/31/2025       871        NaN  105278-IT       272.24
335093       12/31/2025       872        NaN  105276-IT       281.43

[17378 rows x 5 columns]

In [49]:
# Convert Transaction date to datetime
ct_sales["Transaction Date"] = pd.to_datetime(ct_sales["Transaction Date"]) # Currently, "Transaction Date" is a str type, we want to convert it to datetime to manipulate it
ct_sales["Date"] = ct_sales["Transaction Date"].dt.to_period("M")

In [50]:
# Connecticut's Monthly revenue from 2022-2025
ct_monthly_revenue = ct_sales.groupby("Date")[["Sale Amount"]].sum()
ct_monthly_revenue

         Sale Amount
Date
2022-01     29958.25
2022-02     25563.98
2022-03     33995.57
2022-04     31587.12
2022-05     37953.48
2022-06     32008.85
2022-07     30656.27
2022-08     42881.99
2022-09     30369.64
2022-10     43646.37
2022-11     25950.41
2022-12     34680.64
2023-01     38351.45
2023-02     53435.37
2023-03     50828.54
2023-04     45747.20
2023-05     39215.78
2023-06     39754.07
2023-07     49592.69
2023-08     48445.34
2023-09     49175.79
2023-10     45347.65
2023-11     42683.73
2023-12     50446.82
2024-01     57974.76
2024-02     49206.33
2024-03     46044.68
2024-04     38918.30
2024-05     41203.81
2024-06     48142.95
2024-07     48445.34
2024-08     49633.16
2024-09     44890.28
2024-10     43061.44
2024-11     50069.11
2024-12     38351.45
2025-01     68601.89
2025-02     55131.75
2025-03     69261.43
2025-04     58288.72
2025-05     66996.15
2025-06     60671.67
2025-07     88590.03
2025-08     77048.51
2025-09     71032.14
2025-10    115828.46
2025-11     59762.07
2025-12     92791.01

In [51]:
# Finding New York's monthly total revenue
ny_sales = store_sales[store_sales["Store ID"].isin(ny_id)]
ny_sales

       Transaction Date  Store ID  RewardsID   Prod Num  Sale Amount
117            1/1/2022       840        NaN  105315-IT        34.43
118            1/1/2022       842        NaN  105346-IT       318.96
119            1/1/2022       843       47.0   105349-M         8.00
120            1/1/2022       844        NaN   105446-B        12.70
121            1/1/2022       845        NaN   105447-M        50.96
...                 ...       ...        ...        ...          ...
335069       12/31/2025       850        NaN   105376-M        44.50
335070       12/31/2025       850      427.0   105608-A        12.15
335071       12/31/2025       851        NaN   105812-B        25.45
335072       12/31/2025       851        NaN   105760-S         7.85
335073       12/31/2025       851        NaN  105305-IT        76.36

[31039 rows x 5 columns]

In [52]:
# Convert Transaction date to datetime
ny_sales["Transaction Date"] = pd.to_datetime(ny_sales["Transaction Date"]) 
ny_sales["Date"] = ny_sales["Transaction Date"].dt.to_period("M")

In [53]:
# New York's Monthly revenue from 2022-2025
ny_monthly_revenue = ny_sales.groupby("Date")[["Sale Amount"]].sum()
ny_monthly_revenue

         Sale Amount
Date
2022-01     58635.53
2022-02     60262.97
2022-03     57143.40
2022-04     56880.02
2022-05     51805.22
2022-06     60549.86
2022-07     56250.74
2022-08     55052.53
2022-09     60495.63
2022-10     56896.98
2022-11     58402.69
2022-12     55006.46
2023-01     85210.01
2023-02     86906.65
2023-03     79964.16
2023-04     97173.99
2023-05    101370.73
2023-06     83465.90
2023-07     90818.80
2023-08     89422.22
2023-09     89196.88
2023-10     85095.72
2023-11     79627.33
2023-12     75904.66
2024-01     94306.43
2024-02     75083.70
2024-03     99439.50
2024-04     99105.22
2024-05     87328.99
2024-06     86955.71
2024-07     89422.22
2024-08     91189.41
2024-09     83103.19
2024-10     80543.34
2024-11     74988.65
2024-12     85210.01
2025-01    135193.89
2025-02    104990.83
2025-03    119415.68
2025-04    117652.02
2025-05    119352.07
2025-06    135192.03
2025-07    126976.23
2025-08    133776.60
2025-09    119597.00
2025-10    185241.67
2025-11    126941.06
2025-12    128272.56

**How would you rank the sales performance of each store in each sales territory? Which are the top-performing stores?**

In [ ]:
# Ranking on stores in Connecticut
ct_rank = ct_sales.groupby("Store ID")[["Sale Amount"]].sum()

In [ ]:
ct_rank = ct_rank.sort_values("Sale Amount", ascending=False)
ct_rank = ct_rank.merge(ct_info[["Store ID", "Store Location"]], on="Store ID") # merged the 2 DF, to add in store location column
ct_rank

   Store ID  Sale Amount     Store Location
0       870    331116.76         New London
1       865    322100.07         Bridgeport
2       867    309592.06           Hartford
3       872    295651.17          Waterbury
4       869    286779.43          New Haven
5       868    286217.15  Litchfield County
6       866    283455.62             Darien
7       871    277310.18       Old Saybrook

In [64]:
ny_rank = ny_sales.groupby("Store ID")[["Sale Amount"]].sum()

In [65]:
ny_rank = ny_rank.sort_values("Sale Amount", ascending=False)
ny_rank = ny_rank.merge(ny_info[["Store ID", "Store Location"]], on="Store ID")
ny_rank

    Store ID  Sale Amount Store Location
0        850    621565.02       New York
1        847    607148.21      Rochester
2        846    334175.88    Poestenkill
3        841    314979.99        Buffalo
4        842    313971.65         Elmira
5        843    313920.05         Ithaca
6        845    311520.52    Plattsburgh
7        840    310389.02         Albany
8        848    306998.14       Syracuse
9        849    304732.76       Brooklyn
10       844    302862.71         Oswego
11       851    288553.14         Queens

**Comparing the customer ID from the customer list data with the rewards ID from the sales data, who were the top customers in each sales territory?**

In [ ]:
# Connecticut first
# "customer_list.csv" uses "|" so need to load correctly
cust_list = pd.read_csv("customer_list.csv", sep="|")
cust_list.head() # verify it works

,cust_id,date,time,name,email,phone,sms-opt-out
0,1,2023-03-15,08:45:12,Rachel,rachel@centralperk.coffee,212-555-1001,N
1,2,2023-05-22,12:30:45,R. Geller,rossg@centralperk.coffee,212-555-1002,N
2,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
3,4,2023-09-01,21:05:33,Chandler Bing,chandlerb@centralperk.coffee,212-555-1004,Y
4,5,2023-11-18,14:22:10,Joey,howyoudoing@centralperk.coffee,212-555-1005,N

In [70]:
# Now need to remove the NaN values in the RewardID column
ct_cust = ct_sales[ct_sales["RewardsID"].notna()] # only keep rows, that has a RewardID

print(ct_sales.shape)
print(ct_cust.shape)

(17378, 6)
(1848, 6)

In [83]:
# Now merge 
ct_cust_sales = ct_cust.merge(cust_list, left_on="RewardsID", right_on="cust_id")
ct_cust_sales.head()

,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Date,cust_id_x,date_x,time_x,name_x,...,email_y,phone_y,sms-opt-out _y,cust_id,date,time,name,email,phone,sms-opt-out
0,2022-01-02,868,441.0,105478-B,17.70,2022-01,441,2023-04-28,13:15:05,Uncle Leo,...,hello@vandelayindustries.com,212-555-2410,N,441,2023-04-28,13:15:05,Uncle Leo,hello@vandelayindustries.com,212-555-2410,N
1,2022-01-02,872,231.0,105481-T,74.50,2022-01,231,2023-09-18,12:35:40,Maria LaGuerta,...,maria@miamimetro.gov,305-555-1606,N,231,2023-09-18,12:35:40,Maria LaGuerta,maria@miamimetro.gov,305-555-1606,N
2,2022-01-03,867,416.0,105548-M,6.00,2022-01,416,2023-11-05,06:00:55,Grover,...,grover@sesamestreet.org,212-555-2205,N,416,2023-11-05,06:00:55,Grover,grover@sesamestreet.org,212-555-2205,N
3,2022-01-05,865,3.0,105664-A,12.12,2022-01,3,2023-07-09,18:15:27,Monica Geller,...,chefmonica@centralperk.coffee,212-555-1003,N,3,2023-07-09,18:15:27,Monica Geller,chefmonica@centralperk.coffee,212-555-1003,N
4,2022-01-07,867,95.0,105384-A,23.44,2022-01,95,2024-04-05,11:25:35,Leo Markus,...,leo@willandgrace.nyc,212-555-9210,N,95,2024-04-05,11:25:35,Leo Markus,leo@willandgrace.nyc,212-555-9210,N

In [ ]:
ct_cust_sales = ct_cust_sales[["RewardsID", "name", "Sale Amount"]] # cleaned up the columns I needed and did not need
ct_cust_sales

      RewardsID            name  Sale Amount
0         441.0       Uncle Leo        17.70
1         231.0  Maria LaGuerta        74.50
2         416.0          Grover         6.00
3           3.0   Monica Geller        12.12
4          95.0      Leo Markus        23.44
...         ...             ...          ...
1843       50.0           Creed        17.70
1844      311.0    Dawn Summers       134.80
1845      165.0    Ken Franklin        19.36
1846       57.0     Ron Swanson        61.14
1847      307.0           Angel        71.80

[1848 rows x 3 columns]

In [ ]:
# now to find the best customer in Connecticut
ct_cust_sales = ct_cust_sales.groupby(["RewardsID", "name"])[["Sale Amount"]].sum().sort_values("Sale Amount", ascending=False)
ct_cust_sales.head()

# Marie S. is the top customer in Connecticut with $4388.87

                      Sale Amount
RewardsID name
18.0      Marie S.        4388.87
21.0      Jon Snow        3676.21
322.0     Fox Mulder      3569.60
365.0     Pugsley A.      3009.29
104.0     Helen M.        2886.72

In [98]:
# New York's Best Customer
# Only want customers thaty have a RewardsID
ny_cust = ny_sales[ny_sales["RewardsID"].notna()]

In [97]:
# merging DataFrames
ny_cust_sales = ny_cust.merge(cust_list, left_on="RewardsID", right_on="cust_id")
ny_cust_sales.head()

,Transaction Date,Store ID,RewardsID,Prod Num,Sale Amount,Date,cust_id,date,time,name,email,phone,sms-opt-out
0,2022-01-01,843,47.0,105349-M,8.00,2022-01,47,2024-04-01,15:05:45,Stanley H.,stanley@dundermifflin.com,570-555-5007,N
1,2022-01-02,848,139.0,105356-S,13.13,2022-01,139,2023-06-10,20:55:10,Ashley A.,ashley@genoa.city,213-555-9704,N
2,2022-01-03,842,375.0,105608-A,12.15,2022-01,375,2023-08-21,21:35:30,C.J. Cregg,cj@westwing.gov,202-555-1804,Y
3,2022-01-04,841,47.0,105626-S,6.02,2022-01,47,2024-04-01,15:05:45,Stanley H.,stanley@dundermifflin.com,570-555-5007,N
4,2022-01-05,841,325.0,105546-T,212.32,2022-01,325,2024-01-31,22:40:00,Cigarette Smoking Man,csm@fbi.gov,202-555-1304,Y

In [100]:
ny_cust_sales = ny_cust_sales.groupby(["cust_id", "name"])[["Sale Amount"]].sum().sort_values("Sale Amount", ascending=False)
ny_cust_sales.head()

# Julian Bashir is the top customer in New York with $6039.32

                       Sale Amount
cust_id name
300     Julian Bashir      6039.32
129     Jason Morgan       3918.72
188     Mellie Grant       3805.61
483     Peggy Olson        3504.20
199     Gonzo              3441.19